mod client;
pub use client::ImageEvalClient;
use std::{error::Error, fmt::Display};

use async_openai::{
    Client,
    config::OpenAIConfig,
    types::responses::{
        CreateResponseArgs, ImageDetail, InputContent, InputImageContent, InputMessage, InputRole,
        OutputItem, OutputMessageContent,
    },
};
use base64::{Engine as _, engine::general_purpose};

pub const DEFAULT_OPENAI_MODEL: &str = "gpt-4.1-mini";

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ImageEvaluationResult {
    /// The full raw text response generated by the model
    #[serde(alias = "full_model_output")]
    pub full_model_output: String,
    /// For example if the image was a HVAC unit with a tag 123, it might suggest "_UNIT_123". Should be None if no relevant
    /// info can be inferred from the picture
    #[serde(alias = "new_suggested_filepath_suffix")]
    pub new_suggested_filepath_suffix: Option<String>,
    /// A brief description 1-2 sentences of what the model sees in the image
    #[serde(alias = "brief_description")]
    pub brief_description: String,
    #[serde(alias = "original_image_path")]
    pub original_image_path: String,
}

fn parse_model_response_into_image_eval_result(
    model_response: &str,
    image_path: &str,
) -> Result<ImageEvaluationResult, Box<dyn Error>> {
    // Try to parse as JSON first
    let json_result: Result<serde_json::Value, _> = serde_json::from_str(model_response);

    match json_result {
        Ok(json) => {
            // Extract fields from JSON
            let filepath_suffix = json
                .get("filepath_suffix")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string())
                .filter(|s| !s.is_empty());

            let brief_description = json
                .get("brief_description")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string())
                .unwrap_or_else(|| "No description provided".to_string());

            Ok(ImageEvaluationResult {
                full_model_output: model_response.to_string(),
                new_suggested_filepath_suffix: filepath_suffix,
                brief_description,
                original_image_path: image_path.to_string(),
            })
        }
        Err(_) => {
            // If JSON parsing fails, try to extract from markdown code blocks
            let cleaned = model_response
                .trim()
                .trim_start_matches("```json")
                .trim_start_matches("```")
                .trim_end_matches("```")
                .trim();

            match serde_json::from_str::<serde_json::Value>(cleaned) {
                Ok(json) => {
                    let filepath_suffix = json
                        .get("filepath_suffix")
                        .and_then(|v| v.as_str())
                        .map(|s| s.to_string())
                        .filter(|s| !s.is_empty());

                    let brief_description = json
                        .get("brief_description")
                        .and_then(|v| v.as_str())
                        .map(|s| s.to_string())
                        .unwrap_or_else(|| "No description provided".to_string());

                    Ok(ImageEvaluationResult {
                        full_model_output: model_response.to_string(),
                        new_suggested_filepath_suffix: filepath_suffix,
                        brief_description,
                        original_image_path: image_path.to_string(),
                    })
                }
                Err(_) => {
                    // Fallback: return the raw response with no parsing
                    Ok(ImageEvaluationResult {
                        full_model_output: model_response.to_string(),
                        new_suggested_filepath_suffix: None,
                        brief_description: "Failed to parse model response".to_string(),
                        original_image_path: image_path.to_string(),
                    })
                }
            }
        }
    }
}

pub enum ImageEvaluationError {
    EvalError(Box<dyn Error>),
    AnalyzeImageErr(Box<dyn Error>),
}
impl Display for ImageEvaluationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ImageEvaluationError::EvalError(e) => write!(f, "Evaluation error: {}", e),
            ImageEvaluationError::AnalyzeImageErr(e) => write!(f, "Analysis error: {}", e),
        }
    }
}

/// The default analysis instructions. Users can replace this with a custom prompt.
pub const DEFAULT_ANALYSIS_PROMPT: &str = r#"Analyze this image of mechanical equipment.

1. Identify any unit tags, serial numbers, model numbers, or identifying labels visible in the image.
2. Determine the equipment type (e.g. HVAC unit, pump, compressor, boiler, electrical panel).
3. Note any other important identifying information such as manufacturer, capacity ratings, or installation details.

For the filepath_suffix, use the most specific identifier you find (e.g. "_UNIT_123", "_SERIAL_ABC456", "_MODEL_XYZ789"). Prefer unit tags over serial numbers, and serial numbers over model numbers.
For the brief_description, state the equipment type and mention the identifier you used for the suffix."#;

/// JSON format instructions that are always appended to the prompt (custom or default).
const JSON_FORMAT_INSTRUCTIONS: &str = r#"Based on the analysis instructions above, respond with ONLY a valid JSON object containing exactly these two fields:

{
  "filepath_suffix": "<a short suffix based on what you identified, or null>",
  "brief_description": "<1-2 sentence summary of what you see>"
}

- "filepath_suffix": A concise identifier derived from your analysis (e.g. "_UNIT_123", "_VALVE_A7"). Use underscores, max 50 characters. Set to null if nothing useful can be identified.
- "brief_description": A 1-2 sentence summary of your observations.

If the image is not relevant to the analysis instructions, set both fields to null.
Do not include any text outside the JSON object."#;

const DEFAULT_TEMPERATURE: f32 = 0.3;

async fn evaluate_image(
    client: &Client<OpenAIConfig>,
    image_path: String,
    model: String,
    prompt: Option<String>,
    temperature: Option<f32>,
) -> Result<ImageEvaluationResult, ImageEvaluationError> {
    if let Some(ref prompt) = prompt {
        println!("Evaluating image with custom prompt: {}", prompt);
    } else {
        println!("Evaluating image with default prompt");
    }
    let analysis = prompt.unwrap_or_else(|| DEFAULT_ANALYSIS_PROMPT.to_string());
    let full_prompt = format!("{}\n\n{}", analysis, JSON_FORMAT_INSTRUCTIONS);

    let img_path2 = image_path.clone();

    let temperature = temperature.unwrap_or(DEFAULT_TEMPERATURE);
    println!("Temperature: {}", temperature);

    let args = AnalyzeImageArgs {
        image_path,
        model,
        prompt: full_prompt,
        temperature,
    };

    let result = analyze_image(client, args)
        .await
        .map_err(|e| ImageEvaluationError::AnalyzeImageErr(e))?;

    let parsed = parse_model_response_into_image_eval_result(&result, &img_path2)
        .map_err(|e| ImageEvaluationError::EvalError(e))?;

    Ok(parsed)
}

async fn evaluate_images_raw(
    client: &Client<OpenAIConfig>,
    prompt: String,
    image_paths: Vec<String>,
    model: String,
    temperature: f32,
) -> Result<String, String> {
    let args = AnalyzeMultipleImageArgs {
        image_paths,
        model,
        prompt,
        temperature,
    };
    analyze_images(client, args)
        .await
        .map_err(|e| e.to_string())
}

async fn evaluate_image_raw(
    client: &Client<OpenAIConfig>,
    prompt: String,
    image_path: String,
    model: String,
    temperature: f32,
) -> Result<String, String> {
    let args = AnalyzeImageArgs {
        image_path,
        model,
        prompt,
        temperature,
    };

    let result = analyze_image(client, args)
        .await
        .map_err(|e| e.to_string())?;

    Ok(result)
}

pub struct AnalyzeMultipleImageArgs {
    pub image_paths: Vec<String>,
    pub model: String,
    pub prompt: String,
    pub temperature: f32,
}

pub struct AnalyzeImageArgs {
    pub image_path: String,
    pub model: String,
    pub prompt: String,
    pub temperature: f32,
}

fn mime_type_for_image_path(image_path: &str) -> Result<&'static str, Box<dyn Error>> {
    if image_path.ends_with(".jpg") || image_path.ends_with(".jpeg") {
        Ok("image/jpeg")
    } else if image_path.ends_with(".png") {
        Ok("image/png")
    } else if image_path.ends_with(".gif") {
        Ok("image/gif")
    } else if image_path.ends_with(".webp") {
        Ok("image/webp")
    } else {
        Err(format!("Unsupported image format: {}", image_path).into())
    }
}

fn encode_image_as_data_uri(image_path: &str) -> Result<String, Box<dyn Error>> {
    if image_path.is_empty() {
        return Err("Image path is empty".into());
    }

    let image_data = std::fs::read(image_path)?;
    let base64_encoded = general_purpose::STANDARD.encode(&image_data);
    let mime_type = mime_type_for_image_path(image_path)?;

    Ok(format!("data:{};base64,{}", mime_type, base64_encoded))
}

fn input_image_content(image_data_uri: String) -> InputContent {
    InputContent::InputImage(InputImageContent {
        detail: ImageDetail::Auto,
        image_url: Some(image_data_uri),
        file_id: None,
    })
}

fn extract_text_from_response(output: Vec<OutputItem>) -> Result<String, Box<dyn Error>> {
    let mut text_response = Vec::new();

    for item in output {
        match item {
            OutputItem::Message(message) => {
                for content in message.content {
                    match content {
                        OutputMessageContent::OutputText(text) => {
                            text_response.push(text.text);
                        }
                        OutputMessageContent::Refusal(refusal) => {
                            println!("Refusal: {:?}", refusal.refusal);
                        }
                    }
                }
            }
            _ => println!("Other output: {:?}", item),
        }
    }

    Ok(text_response.join(" "))
}

async fn send_image_analysis_request(
    client: &Client<OpenAIConfig>,
    model: String,
    prompt: String,
    temperature: f32,
    image_data_uris: Vec<String>,
) -> Result<String, Box<dyn Error>> {
    if image_data_uris.is_empty() {
        return Err("No images provided".into());
    }

    let mut content = vec![prompt.into()];
    content.extend(image_data_uris.into_iter().map(input_image_content));

    let request = CreateResponseArgs::default()
        .temperature(temperature)
        .model(model)
        .input(InputMessage {
            content,
            role: InputRole::User,
            status: None,
        })
        .build()?;

    let response = client.responses().create(request).await?;
    extract_text_from_response(response.output)
}

async fn analyze_images(
    client: &Client<OpenAIConfig>,
    args: AnalyzeMultipleImageArgs,
) -> Result<String, Box<dyn Error>> {
    if args.image_paths.is_empty() {
        return Err("No image paths provided".into());
    }

    let image_data_uris = args
        .image_paths
        .iter()
        .map(|path| encode_image_as_data_uri(path))
        .collect::<Result<Vec<_>, _>>()?;

    send_image_analysis_request(
        client,
        args.model,
        args.prompt,
        args.temperature,
        image_data_uris,
    )
    .await
}

/// Send an image to the OpenAI client
async fn analyze_image(
    client: &Client<OpenAIConfig>,
    args: AnalyzeImageArgs,
) -> Result<String, Box<dyn Error>> {
    let image_data_uri = encode_image_as_data_uri(&args.image_path)?;

    send_image_analysis_request(
        client,
        args.model,
        args.prompt,
        args.temperature,
        vec![image_data_uri],
    )
    .await
}
